apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: dev-rabbit-svc
  namespace: dev
  labels:
    app: dev
    tier: queue
    version: v1  
spec:
  type: NodePort
  ports:
    - name: rabbitmq-mgmt-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rabbitmq-amqp-port
      protocol: TCP
      port: 5672
      targetPort: 5672  
  selector:
    app: dev
    tier: queue
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-rabbit-dep
  namespace: dev 
spec:
  selector:
    matchLabels:
      app: dev
      tier: queue
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: dev
        tier: queue
        version: v1
    spec:
      containers:
        - name: rabbitmq
          image: jcmds/rabbitmq:3.7-management-alpine-delayed-exchange
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
          ports:
            - containerPort: 5672
            - containerPort: 15672
           